import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Bot, Clock, History, Sparkles } from 'lucide-react';
import { api } from '../lib/api.js';
import { Callout, EmptyState, Eyebrow, Loading } from '../components/ui.jsx';

/**
 * AgentActivity — /agent-activity
 *
 * Audit log timeline showing all decisions, context evaluations, and recommendations
 * generated by the EduPath 2.0 AI Agent.
 */

export default function AgentActivity() {
  const [activities, setActivities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.agent.activity();
      setActivities(res.activities || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (loading) return <Loading label="Loading agent activity log" />;
  if (error) return <Callout tone="error">{error}</Callout>;

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <header>
        <Link to="/ai-agent" className="btn-ghost px-0 mb-4 inline-flex text-xs">
          <ArrowLeft size={14} aria-hidden="true" />
          Back to AI Chat
        </Link>
        <div className="flex items-center gap-3">
          <History size={24} className="text-effort shrink-0" aria-hidden="true" />
          <div>
            <h1 className="text-2xl font-semibold">Agent Activity Timeline</h1>
            <p className="text-xs text-ink-soft mt-0.5">
              Transparent log of AI evaluations, weakness detections, and recommendations.
            </p>
          </div>
        </div>
      </header>

      {activities.length === 0 ? (
        <EmptyState title="No agent activities logged yet">
          Interact with the AI Agent or complete assessments to log grounded agent actions.
        </EmptyState>
      ) : (
        <ol className="relative border-l border-rule ml-4 space-y-6 py-2">
          {activities.map((act) => (
            <li key={act._id} className="ml-6 space-y-1">
              <span className="absolute -left-3 flex items-center justify-center w-6 h-6 rounded-full bg-paper border border-effort text-effort">
                <Bot size={12} />
              </span>

              <div className="flex items-baseline justify-between gap-4">
                <h3 className="text-sm font-semibold text-ink">{act.action}</h3>
                <span className="text-xs font-mono text-ink-faint shrink-0">
                  {new Date(act.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · {new Date(act.timestamp).toLocaleDateString()}
                </span>
              </div>

              {act.reason && <p className="text-xs text-ink-soft leading-relaxed">{act.reason}</p>}
            </li>
          ))}
        </ol>
      )}
    </div>
  );
}
